/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ColorEnum: typeof import('./packages/lite-flow/src/types/enums')['ColorEnum']
  const EffectScope: typeof import('vue')['EffectScope']
  const LiteFlowProps: typeof import('./packages/lite-flow/src/types/props')['LiteFlowProps']
  const NodeStateEnum: typeof import('./packages/lite-flow/src/types/enums')['NodeStateEnum']
  const NodeTypeEnum: typeof import('./packages/lite-flow/src/types/enums')['NodeTypeEnum']
  const common: typeof import('./packages/lite-flow/src/nodes/common/common')['default']
  const commonNode: typeof import('./packages/lite-flow/src/nodes/common/common-node')['default']
  const computed: typeof import('vue')['computed']
  const connection: typeof import('./packages/lite-flow/src/edges/connection')['default']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const effectScope: typeof import('vue')['effectScope']
  const end: typeof import('./packages/lite-flow/src/nodes/end/end')['default']
  const endNode: typeof import('./packages/lite-flow/src/nodes/end/end-node')['default']
  const for: typeof import('./packages/lite-flow/src/nodes/for/for')['default']
  const forNode: typeof import('./packages/lite-flow/src/nodes/for/for-node')['default']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getCurrentWatcher: typeof import('vue')['getCurrentWatcher']
  const groupMap: typeof import('./packages/lite-flow/src/types/nodes')['groupMap']
  const h: typeof import('vue')['h']
  const if: typeof import('./packages/lite-flow/src/nodes/if/if')['default']
  const ifNode: typeof import('./packages/lite-flow/src/nodes/if/if-node')['default']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const isShallow: typeof import('vue')['isShallow']
  const iterator: typeof import('./packages/lite-flow/src/nodes/iterator/iterator-node')['default']
  const iteratorNode: typeof import('./packages/lite-flow/src/nodes/iterator/iterator-node')['default']
  const liteFlow: typeof import('./packages/lite-flow/index')['default']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const nodeTypeDef: typeof import('./packages/lite-flow/src/types/nodes')['nodeTypeDef']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const parseSvg: typeof import('./packages/lite-flow/src/tool')['parseSvg']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const start: typeof import('./packages/lite-flow/src/nodes/start/start')['default']
  const startNode: typeof import('./packages/lite-flow/src/nodes/start/start-node')['default']
  const summary: typeof import('./packages/lite-flow/src/nodes/summary/summary')['default']
  const summaryNode: typeof import('./packages/lite-flow/src/nodes/summary/summary-node')['default']
  const switch: typeof import('./packages/lite-flow/src/nodes/switch/switch')['default']
  const switchNode: typeof import('./packages/lite-flow/src/nodes/switch/switch-node')['default']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAttrs: typeof import('vue')['useAttrs']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useId: typeof import('vue')['useId']
  const useModel: typeof import('vue')['useModel']
  const useSlots: typeof import('vue')['useSlots']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const when: typeof import('./packages/lite-flow/src/nodes/when/when')['default']
  const whenNode: typeof import('./packages/lite-flow/src/nodes/when/when-node')['default']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ColorEnum, NodeStateEnum, NodeTypeEnum } from './packages/lite-flow/src/types/enums'
  import('./packages/lite-flow/src/types/enums')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ColorEnum: UnwrapRef<typeof import('./packages/lite-flow/src/types/enums')['ColorEnum']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly LiteFlowProps: UnwrapRef<typeof import('./packages/lite-flow/src/types/props')['LiteFlowProps']>
    readonly NodeStateEnum: UnwrapRef<typeof import('./packages/lite-flow/src/types/enums')['NodeStateEnum']>
    readonly NodeTypeEnum: UnwrapRef<typeof import('./packages/lite-flow/src/types/enums')['NodeTypeEnum']>
    readonly commonNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/common/common-node')['default']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly endNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/end/end-node')['default']>
    readonly forNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/for/for-node')['default']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly groupMap: UnwrapRef<typeof import('./packages/lite-flow/src/types/nodes')['groupMap']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly ifNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/if/if-node')['default']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly iteratorNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/iterator/iterator-node')['default']>
    readonly liteFlow: UnwrapRef<typeof import('./packages/lite-flow/index')['default']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly nodeTypeDef: UnwrapRef<typeof import('./packages/lite-flow/src/types/nodes')['nodeTypeDef']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parseSvg: UnwrapRef<typeof import('./packages/lite-flow/src/tool')['parseSvg']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly startNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/start/start-node')['default']>
    readonly summaryNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/summary/summary-node')['default']>
    readonly switchNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/switch/switch-node')['default']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly whenNode: UnwrapRef<typeof import('./packages/lite-flow/src/nodes/when/when-node')['default']>
  }
}